config/routes.rb
Rails.application.routes.draw do
  resources :images
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/image.rb
class Image < ApplicationRecord
  has_one_attached :image
  validates :image, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  def index
    @images = Image.all
  end

  def new
    @image = Image.new
  end

  def create
    @image = Image.new(image_params)
    if @image.save
      redirect_to images_path
    else
      render :new
    end
  end

  def edit
    @image = Image.find(params[:id])
  end

  def update
    @image = Image.find(params[:id])
    if @image.update(image_params)
      sleep(3) #S3への画像反映のタイムラグを考慮して３秒待機
      redirect_to image_url(@image)
    else
      render :edit
    end
  end

  def show
    @image = Image.find(params[:id])
    #参照先のS3オブジェクトURLを作成
    @image_url = "https://practice-img-files-resize.s3-ap-northeast-1.amazonaws.com/#{@image.image.key}-thumbnail.#{@image.image.content_type.split('/').pop}"
  end

  def destroy
    @image = Image.find(params[:id])
    @image.destroy
    redirect_to images_path
  end

  private

  def image_params
    params.require(:image).permit(:name, :image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/views/images/_new_validation.html.erb
<script>

  var nameField = document.querySelector('#name');
  var nameError = document.querySelector("#name-error");
  var nameForm = document.querySelector("#name-form");

  var imageField = document.querySelector("#image");
  var imageError = document.querySelector("#image-error");
  var imageForm = document.getElementById("#image-form");

  nameForm.addEventListener('input', ()=>{
    if (nameForm.value === "") {
      nameError.textContent = "名前を入力してください";
      nameError.style.color = "red";
      nameField.classList.add("name-form-error");
      nameField.classList.remove("name-form-success");
    } else if(nameForm.value.length < 3){
      nameError.textContent = "3文字以上入力してください";
      nameError.style.color = "orange";
      nameField.classList.add("name-form-error");
      nameField.classList.remove("name-form-success");
    } else {
      nameError.textContent = "";
      nameField.classList.remove("name-form");
      nameField.classList.add("name-form-success");
    }
  });
  
  // imageForm.addEventListener({
  //   if (imageForm.value == null) {
  //     imageField.classList.add("image-form-success");
  //   }
  // });



</script>

app/views/images/edit.html.erb
<h1>Images#edit</h1>
<%= form_with model: @image, local: true do |form| %>
  <%= form.label :name %>
  <%= form.text_field :name %>
  <%= form.label :image %>
  <%= form.file_field :image %>
  <p><%= form.submit "Edit" %></p>
<% end %>

app/views/images/index.html.erb
<h1>Image#index</h1>
<div>
  <%= link_to "新規作成", new_image_path %>
</div>

<% @images.each do |image| %>
  <h2><%= image.name %></h2>
  <%= link_to "詳細", image_path(image) %>
  <%= link_to "削除", image_path(image), method: :delete %>
<% end %>

<span id="back">
  <a href="#">
    <%= image_tag "arrow.png" %>
  </a>
</span>

<%= javascript_include_tag "scroll.js" %>

app/views/images/new.html.erb
<h1>Images#new</h1>
<%= form_with model: @image, id: "imageForm", local: true do |form| %>
  <div id="name" style="margin-bottom: 3px";>
    <%= form.label :name %>
    <%= form.text_field :name, id: "name-form" %>
  </div>
  <div id="name-error"></div>

  <div id="image">
    <%= form.label :image %>
    <%= form.file_field :image, id: "image-form" %>
  </div>
  <div id="image-error"></div>
  <p><%= form.submit "Upload" %></p>
<% end %>

<%= render "new_validation" %>

app/views/images/show.html.erb
<h1>Images#show</h1>
<h2><%= @image.name %></h2>
<div>
  <%= image_tag @image_url %>
</div>
<p><%= link_to "編集", edit_image_path(@image) %></p>
<p><%= link_to "戻る", images_path %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ImageUploadApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>